<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright (c) 2025 天启雨数科技有限公司 
  All rights reserved. 
  注意： 
  本项目源代码由天启雨数科技有限公司原创开发，版权所有。 
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.aryn</groupId>
        <artifactId>aryn-common</artifactId>
        <version>3.2.1</version>
    </parent>

    <artifactId>aryn-common-redis</artifactId>
    <packaging>jar</packaging>
    <description>redis缓存工具模块</description>

    <dependencies>
        <!--common-->
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-core</artifactId>
        </dependency>
        <!--缓存依赖-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
    </dependencies>


</project>