<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright (c) 2025 天启雨数科技有限公司 
  All rights reserved. 
  注意： 
  本项目源代码由天启雨数科技有限公司原创开发，版权所有。 
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>aryn-user</artifactId>
        <groupId>com.aryn</groupId>
        <version>3.2.1</version>
    </parent>
    <artifactId>aryn-user-biz</artifactId>
    <dependencies>
        <!--注册中心客户端-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <!--配置中心客户端-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
        </dependency>
        <!--web 模块-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--数据库-->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-3-starter</artifactId>
        </dependency>
        <!--            mybatis-plus-->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>
        <!--            安全模块-->
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-security</artifactId>
        </dependency>
        <!--           日志模块-->
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-log</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-user-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-promotion-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-dubbo</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.aryn</groupId>
                    <artifactId>aryn-common-mybatis</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>cloud</id>
            <activation>
                <!-- 默认环境 -->
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>boot</id>
        </profile>
    </profiles>
</project>
