<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright (c) 2025 天启雨数科技有限公司 
  All rights reserved. 
  注意： 
  本项目源代码由天启雨数科技有限公司原创开发，版权所有。 
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.aryn</groupId>
        <artifactId>aryn-common</artifactId>
        <version>3.2.1</version>
    </parent>

    <artifactId>aryn-common-swagger</artifactId>


    <dependencies>
        <!--common-->
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.xingfudeshi</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>io.swagger.core.v3</groupId>
                    <artifactId>swagger-annotations</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-commons</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

</project>