<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright (c) 2025 天启雨数科技有限公司 
  All rights reserved. 
  注意： 
  本项目源代码由天启雨数科技有限公司原创开发，版权所有。 
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>aryn-common</artifactId>
        <groupId>com.aryn</groupId>
        <version>3.2.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <description>Meilisearch 搜索服务模块</description>
    <artifactId>aryn-common-search</artifactId>
    <packaging>jar</packaging>
    <dependencies>
        <!--common-->
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-core</artifactId>
        </dependency>
        <!-- Meilisearch Java SDK -->
        <dependency>
            <groupId>com.meilisearch.sdk</groupId>
            <artifactId>meilisearch-java</artifactId>
            <version>${meilisearch.version}</version>
        </dependency>
    </dependencies>
</project>