<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright (c) 2025 天启雨数科技有限公司 
  All rights reserved. 
  注意： 
  本项目源代码由天启雨数科技有限公司原创开发，版权所有。 
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>aryn</artifactId>
        <groupId>com.aryn</groupId>
        <version>3.2.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>aryn-auth</artifactId>
    <description>认证授权模块</description>
    <packaging>jar</packaging>

    <dependencies>
        <!--注册中心客户端-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <!--配置中心客户端-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!--滑块验证码-->
        <dependency>
            <groupId>com.anji-plus</groupId>
            <artifactId>captcha-spring-boot-starter</artifactId>
        </dependency>
        <!--安全模块-->
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-log</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-user-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-dubbo</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-common-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.aryn</groupId>
            <artifactId>aryn-upms-api</artifactId>
        </dependency>
    </dependencies>
    <profiles>
        <profile>
            <id>cloud</id>
            <activation>
                <!-- 默认环境 -->
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <finalName>${project.artifactId}</finalName>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>repackage</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>boot</id>
        </profile>
    </profiles>
</project>
