<?xml version="1.0" encoding="UTF-8"?>
<!-- 
  Copyright (c) 2025 天启雨数科技有限公司 
  All rights reserved. 
  注意： 
  本项目源代码由天启雨数科技有限公司原创开发，版权所有。 
 -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>aryn</artifactId>
        <groupId>com.aryn</groupId>
        <version>3.2.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <artifactId>aryn-common</artifactId>
    <modules>
        <module>aryn-common-core</module>
        <module>aryn-common-storage</module>
        <module>aryn-common-mybatis</module>
        <module>aryn-common-log</module>
        <module>aryn-common-security</module>
        <module>aryn-common-job</module>
        <module>aryn-common-logistics</module>
        <module>aryn-common-sms</module>
        <module>aryn-common-redis</module>
        <module>aryn-common-dubbo</module>
        <module>aryn-common-sentinel</module>
        <module>aryn-common-seata</module>
        <module>aryn-common-swagger</module>
        <module>aryn-common-datasource</module>
        <module>aryn-common-excel</module>
        <module>aryn-common-search</module>
    </modules>
</project>
